import { Geist, Geist_Mono } from "next/font/google";
import Header from './common/Header.jsx'
import "./globals.css";
import Footer from "./common/Footer.jsx";
import MainLayout from "./MainLayout.jsx";
import { getFeaturedProducts } from "@/apiServices/productService";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // Server-side fetch of top rated products, pick two random
  let topRatedProducts = [];
  let topRatedStaticPath = "";
  try {
    const res = await getFeaturedProducts({ type: "topRated", limit: 12 });
    const list = Array.isArray(res?.data) ? res.data : [];
    topRatedStaticPath = res?.staticPath || "";
    if (list.length <= 2) {
      topRatedProducts = list;
    } else {
      const indices = new Set();
      while (indices.size < 2) indices.add(Math.floor(Math.random() * list.length));
      topRatedProducts = Array.from(indices).map(i => list[i]);
    }
  } catch (e) {
    topRatedProducts = [];
  }

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MainLayout>
          <Header />
          {children}
          <Footer topRatedProducts={topRatedProducts} staticPath={topRatedStaticPath} />
        </MainLayout>
      </body>
    </html>
  );
}
